export const COUNTER_CHANGE = 'COUNTER_CHANGE';

export const ACTIONS = {
  AUTH: {
    SEND_OTP_ASYNC: 'SEND_OTP_ASYNC',
    SEND_OTP_SUCCESS: 'SEND_OTP_SUCCESS',
    SEND_OTP_FAIL: 'SEND_OTP_FAIL',
    VERIFY_OTP_ASYNC: 'VERIFY_OTP_ASYNC',
    VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',
    VERIFY_OTP_FAIL: 'VERIFY_OTP_FAIL',
    SET_USER_ID: 'SET_USER_ID',
    SET_SUCCESS_FALSE: 'SET_SUCCESS_FALSE',
    SET_DOCUMENTS: 'SET_DOCUMENTS',
    VERIFY_DOCUMENTS: 'VERIFY_DOCUMENTS', // NOTE: TEST ENV ONLY
    LOG_OUT: 'LOG_OUT',
    SET_TOKEN: 'SET_TOKEN',
    FETCH_APP_STATE: 'FETCH_APP_STATE',
    SET_DEVICE_TOKEN_INACTIVE: 'SET_DEVICE_TOKEN_INACTIVE',
    SET_CURRENT_VEHICLE: 'SET_CURRENT_VEHICLE',
  },
  PROFILE: {
    UPDATE_DETAILS_ASYNC: 'UPDATE_DETAILS_ASYNC',
    UPDATE_DETAILS_SUCCESS: 'UPDATE_DETAILS_SUCCESS',
    UPDATE_DETAILS_FAIL: 'UPDATE_DETAILS_FAIL',
    UPLOAD_MEDIA_ASYNC: 'UPLOAD_MEDIA_ASYNC',
    UPLOAD_MEDIA_SUCCESS: 'UPLOAD_MEDIA_SUCCESS',
    UPLOAD_MEDIA_FAIL: 'UPLOAD_MEDIA_FAIL',
    GET_DRIVER: 'GET_DRIVER',
    SET_SUCCESS_FALSE: 'SET_SUCCESS_FALSE',
  },
  HOME: {
    ONLINE_STATUS: 'ONLINE_STATUS',
    UPDATE_FUELLING_VEHICLE_ASYNC: 'UPDATE_FUELLING_VEHICLE_ASYNC',
    UPDATE_FUELLING_VEHICLE_SUCCESS: 'UPDATE_FUELLING_VEHICLE_SUCCESS',
    UPDATE_FUELLING_VEHICLE_FAIL: 'UPDATE_FUELLING_VEHICLE_FAIL',
    SET_SOCKET_CONNECTED: 'SET_SOCKET_CONNECTED',
    CURRENT_LOCATION: 'CURRENT_LOCATION',
    FETCH_SELF_CONSUMPTION_LOGS_ASYNC: 'FETCH_SELF_CONSUMPTION_LOGS_ASYNC',
    FETCH_SELF_CONSUMPTION_LOGS_SUCCESS: 'FETCH_SELF_CONSUMPTION_LOGS_SUCCESS',
    FETCH_SELF_CONSUMPTION_LOGS_FAIL: 'FETCH_SELF_CONSUMPTION_LOGS_FAIL',
    CREATE_SELF_CONSUMPTION_LOGS_ASYNC: 'CREATE_SELF_CONSUMPTION_LOGS_ASYNC',
    CREATE_SELF_CONSUMPTION_LOGS_SUCCESS: 'CREATE_SELF_CONSUMPTION_LOGS_SUCCESS',
    CREATE_SELF_CONSUMPTION_LOGS_FAIL: 'CREATE_SELF_CONSUMPTION_LOGS_FAIL',
  },
  ORDER: {
    FETCH_ORDERS_ASYNC: 'FETCH_ORDERS_ASYNC',
    FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
    FETCH_ORDERS_FAIL: 'FETCH_ORDERS_FAIL',
    FETCH_ORDERS_QUEUE_ASYNC: 'FETCH_ORDERS_QUEUE_ASYNC',
    FETCH_ORDERS_QUEUE_SUCCESS: 'FETCH_ORDERS_QUEUE_SUCCESS',
    FETCH_ORDERS_QUEUE_FAIL: 'FETCH_ORDERS_QUEUE_FAIL',
    ACCEPT_REJECT_ASYNC: 'ACCEPT_REJECT_ASYNC',
    ACCEPT_REJECT_SUCCESS: 'ACCEPT_REJECT_SUCCESS',
    ACCEPT_REJECT_FAIL: 'ACCEPT_REJECT_FAIL',
    SET_ONGOING_ORDER_TO_NULL: 'SET_ONGOING_ORDER_TO_NULL',
    CREATE_OFFLINE_ORDER_ASYNC: 'CREATE_OFFLINE_ORDER_ASYNC',
    CREATE_OFFLINE_ORDER_SUCCESS: 'CREATE_OFFLINE_ORDER_SUCCESS',
    CREATE_OFFLINE_ORDER_FAIL: 'CREATE_OFFLINE_ORDER_FAIL',
    ADJUST_ORDER_ASYNC: 'ADJUST_ORDER_ASYNC',
    ADJUST_ORDER_SUCCESS: 'ADJUST_ORDER_SUCCESS',
    ADJUST_ORDER_FAIL: 'ADJUST_ORDER_FAIL',
    ON_ORDER_FINISHED_ASYNC: 'ON_ORDER_FINISHED_ASYNC',
    SET_ONGOING_ORDER: 'SET_ONGOING_ORDER',
  },
  FUELLING_UNIT: {
    FETCH_FUELLING_UNIT_ASYNC: 'FETCH_FUELLING_UNIT_ASYNC',
    FETCH_FUELLING_UNIT_SUCCESS: 'FETCH_FUELLING_UNIT_SUCCESS',
    FETCH_FUELLING_UNIT_FAIL: 'FETCH_FUELLING_UNIT_FAIL',
    SWITCH_UNIT_ASYNC: 'SWITCH_UNIT_ASYNC',
    SWITCH_UNIT_SUCCESS: 'SWITCH_UNIT_SUCCESS',
    SWITCH_UNIT_FAIL: 'SWITCH_UNIT_FAIL',
  }
};

export const OTP_LENGTH = 4;
export const PHONE_LENGTH = 10;
export const MIN_PROFILE_DETAILS_TEXT_LENGTH = 3;
export const SCREENS = {
  START: 'Start',
  PHONE: 'Phone',
  OTP: 'Otp',
  DETAILS: 'Details',
  DOCUMENT: 'Documents',
  MEDIA: 'Media',
  HOME: 'Home',
  DRIVER_NAVIGATOR: 'DRIVER_NAVIGATOR',
  ORDER_SUCCESSFUL: 'ORDER_SUCCESSFUL'
};
export const AUTH_TOKEN_KEY = 'AUTH_TOKEN';
export const BACK_BUTTON_SIZE = 20;
export const COMMON_ERROR_MESSAGE = 'Something went wrong.';
export const EVENTS = {
  SEND_DRIVER_LOCATION: 'SEND_DRIVER_LOCATION'
};

export const ORDER_STATUSES = {
  CREATED: 0,
  ACCEPTED: 1,
  REJECTED: 2,
  CANCELLED: 3,
  PICKING_FUEL: 4,
  ON_WAY: 5,
  ARRIVED: 6,
  DELIVERED: 7,
  COMPLETED: 8,
  REFUNDED: 9,
  RATED: 10
};

export const ONGOING_ORDER_STATUSES = {
  ACCEPTED: 1,
  PICKING_FUEL: 4,
  ON_WAY: 5,
  ARRIVED: 6,
  DELIVERED: 7,
};

export const COMMON_TEXT_COLOR = '#555';
export const COMMON_TEXT_HEIGHT = 12;
export const SPETROL_RED = '#CA2128';
export const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sept', 'Oct', 'Nov', 'Dec'];
export const NEXT_STATUS = {
  CREATED: 'ACCEPTED',
  ACCEPTED: 'ON_WAY',
  ON_WAY: 'DELIVERED'
};
export const DOCUMENT_NAMES = {
  License: 'License',
  Aadhaar: 'Aadhaar',
  Pic: 'Pic'
};
export const APP_STATES = {
  DOCUMENT_PENDING: 'DOCUMENT_PENDING',
  LOGIN: 'LOGIN',
  READY: 'READY'
};

export const ORDER_STATUSES_STRING = {
  CREATED: 'CREATED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  PICKING_FUEL: 'PICKING_FUEL',
  ON_WAY: 'ON_WAY',
  ARRIVED: 'ARRIVED',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  REFUNDED: 'REFUNDED',
  RATED: 'RATED',
};

export const SPETROL_BLUE = '#0094e9';